### ISSUE TITLE
Spike - Object Mapper

### ISSUE THREAD

**Issue by fedefernandez** [frees-io/freestyle-cassandra#46]
Research and discussion about the Object Mapper feature. 

Basically, we need to describe what features we want and how they should like (in code)

**Comment by fedefernandez** [comment]
We want an *object mapper* with these features:
* Create an *insert prepared statement* from a `case class` type using the [`StatementGenerator`](https://github.com/frees-io/freestyle-cassandra/blob/fda39a7d76aceff2a97a0f5f472b2bab56c1ad13/core/src/main/scala/query/StatementGenerator.scala#L25) and the [`SessionAPI.prepare`](https://github.com/frees-io/freestyle-cassandra/blob/4bd76315aab0684417036a5911577cc3be0cd537/core/src/main/scala/api/SessionAPI.scala#L31) method.
```scala
def insertStatement[F[_], T]: FreeS[F, PreparedStatement]
```
* Populate a previously created *insert prepared statement* with a `case class` using the [`StatementAPI.setByteBufferListByName`](https://github.com/frees-io/freestyle-cassandra/blob/e01b49ed82929a004af94aeecc85970e2224c69e/core/src/main/scala/api/StatementAPI.scala#L58) method.
```scala
def populateStatement[F[_], T](st: PreparedStatement, t: T): FreeS[F, BoundStatement]
```
* Execute* an *insert statement* from a `case class` (* we're returning a `FreeS`, not executing) using the [`StatementGenerator`](https://github.com/frees-io/freestyle-cassandra/blob/fda39a7d76aceff2a97a0f5f472b2bab56c1ad13/core/src/main/scala/query/StatementGenerator.scala#L25), and the [`SessionAPI.executeWithByteBuffer`](https://github.com/frees-io/freestyle-cassandra/blob/4bd76315aab0684417036a5911577cc3be0cd537/core/src/main/scala/api/SessionAPI.scala#L43) method.
```scala
def insert[F[_], T](t: T): FreeS[F, ResultSet]
```
* Execute* a *select statement* from a `case class` (* we're returning a `FreeS`, not executing) using the [`StatementGenerator`](https://github.com/frees-io/freestyle-cassandra/blob/fda39a7d76aceff2a97a0f5f472b2bab56c1ad13/core/src/main/scala/query/StatementGenerator.scala#L25), and the [`SessionAPI.execute`](https://github.com/frees-io/freestyle-cassandra/blob/4bd76315aab0684417036a5911577cc3be0cd537/core/src/main/scala/api/SessionAPI.scala#L35) method.
```scala
def selectStatement[F[_], T]: FreeS[F, ResultSet]
```
* Fetch a list, an option or directly an object from a `ResultSet` using the [`ResultSetAPI`](https://github.com/frees-io/freestyle-cassandra/blob/e486406a7a7498dbb0cb99198fb49a0e17344e35/core/src/main/scala/api/ResultSetAPI.scala#L25).
```scala
def readA[F[_], T](rs: ResultSet): FreeS[F, T]
def readOptionA[F[_], T](rs: ResultSet): FreeS[F, Option[T]]
def readListA[F[_], T](rs: ResultSet): FreeS[F, List[T]]
```

**Comment by fedefernandez** [comment]
Please, @FPerezP could you review? Thanks

**Comment by FPerezP** [comment]
Sounds good, Fede! Thanks a lot!
