### ISSUE TITLE
Select operations

### ISSUE THREAD

**Issue by fedefernandez** [frees-io/freestyle-cassandra#57]
We want to give support for CRUD operations. All operations will be delegated to the [`LowLevelAPI`](https://github.com/frees-io/freestyle-cassandra/blob/029d26e82a95197fe40b72632e1e84a27e39d749/core/src/main/scala/api/LowLevelAPI.scala). The `LowLevelAPI` allows the execution of all async operations of the [`Session`](http://docs.datastax.com/en/drivers/java/3.0/com/datastax/driver/core/Session.html) object from the Datastax driver.

In this ticket, we should take a decision about how the *select operation* will be written with the Datastax driver **and/or** `LowLevelAPI`. 

For example:

**Select**
```
# CQL
SELECT name FROM keyspace1.users WHERE id = <myId>
```

```java
// Datastax code
val prepSt = session.prepare("SELECT name FROM keyspace1.users WHERE id = ?")
val boundStatement = prepSt.bind()
boundStatement.setBytesUnsafe("id", byteBufferCodec.serialize(myId))
val resultSet = session.execute(boundStatement)
```

```scala

def prepareStatement(implicit c: ByteBufferCodec[UUID]): FreeS[F, BoundStatement] =
  lowLevelAPI.prepare("SELECT name FROM keyspace1.users WHERE id = ?") map { st =>
    val boundStatement = st.bind()
    boundStatement.setBytesUnsafe("id", c.serialize(newUser.id))
    boundStatement
}

for {
  prepSt    <- prepareStatement
  resultSet <- lowLevelAPI.execute(prepSt)
} resultSet
```

See the [freestyle-cassandra-example](https://github.com/frees-io/freestyle-cassandra-example/blob/9349de695ee7a7ace8df59a877b0b0cf21396580/low-level-api/src/main/scala/freestyle/cassandra/sample/Program.scala#L35) to learn about how to use `LowLevelAPI`

We should take care of what's the recommended way to make each operation in Cassandra

**Comment by dominv** [comment]
After going through the documentation for Cassandra and the Java Driver for Apache Cassandra, I believe that we should use the way of making the _select operation_ proposed in the description of this issue.

**Comment by dominv** [comment]
After the discussion in issue #61 we have came to the conclusion that we need to add the methods ' bind'  and 'setBytesUnsafe' to the low level API and we've created a new issue #70 to achieve this goal. 

Once this methods have been added the insert operation will be written as follows:

```scala

    import lowLevelAPI._

    for {
      preparedStatement <- prepare("SELECT name FROM keyspace1.users WHERE id = ?")
      boundedStatement  <- bind(preparedStatement)
      _                 <- setBytesUnsafe[UUID](boundedStatement, "id", newUser.id)
      resultSet         <- executeStatement(boundedStatement)
    } resultSet
```

**Comment by fedefernandez** [comment]
Looks great, thanks
