### ISSUE TITLE
Review and tune interpolator operations for create, replace and delete

### ISSUE THREAD

**Issue by fedefernandez** [frees-io/freestyle-cassandra#94]
The current implementation has been developed with the SELECT queries in mind. We should verify that it works for creating, replacing and deleting and create some issues for extra interpolator operations like in #93 focused on creating, replacing and deleting (maybe `as[Int]`?)

**Comment by FPerezP** [comment]
We are currently supporting SELECT, INSERT, UPDATE and DELETE, but no ops to modify the schema: CREATE, TRUNCATE, ALTER, DROP.
Troy supports this OPs under a different parser. We should implement a new Interpolator to make our freestyle-cassandra library be ready for these schema operations. 

I created a ticket to provide a new function for those operations returning NULL (https://github.com/frees-io/freestyle-cassandra/issues/98)
and a different one to support schema related ops (https://github.com/frees-io/freestyle-cassandra/issues/99)

**Comment by fedefernandez** [comment]
Maybe we could rename the interpolators to `ddl` and `dml` instead of `cql`, what do you think?

In any case, this looks good to me.

**Comment by FPerezP** [comment]
As we discussed by phone, IMHO, if an operation is related to Schema or Data manipulation should be transparent for the final user, so I'd keep the single cql syntax instead of splitting it.
